### ISSUE TITLE
UtilTests.listFilesFullPath fails on Ubuntu

### ISSUE THREAD

**Issue by agilarity** [mukatee/osmo#52]
I get this failure when running on Ubuntu 14.04 LTS. It does not fail on Windows 10.
```
Running osmo.common.UtilTests
Tests run: 18, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec <<< FAILURE! - in osmo.common.UtilTests
listFilesFullPath(osmo.common.UtilTests)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: File path should end with file name (afile.txt), was /home/josephc/ws/jee-mars/ws-rnd/osmo-master/osmotester/test-data1/afile2.txt
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at osmo.common.UtilTests.listFilesFullPath(UtilTests.java:273)
```

The root cause is that the test assumes the order in which the files will be returned from the file system.

I recommend changing the test to check that the full path to all the files match the listed path.

Here is the new scenario.
```
Given a folder with some files
When the full path for the files are listed
Then the listed paths will match the full path to each file
```

**Comment by mukatee** [comment]
this should be fixed now, i simply sorted the list. let me know if any issues
